package day07

import kotlin.io.path.Path
import kotlin.io.path.readText
import kotlin.text.indexOf

// each beam split, create new timeline (alternate world)
fun countAllTimelinesThatBeamSplitOpen(diagram: List<String>): Long {
    val firstBeamInitialPointer = diagram.first().indexOf('S')
    var columnIndexToAmountOfBeams = mutableMapOf(firstBeamInitialPointer to 1L)

    diagram.forEach { row ->
        val nextColIndexToBeams = mutableMapOf<Int, Long>()
        for ((index, beams) in columnIndexToAmountOfBeams) {
            if (index < 0 || index >= row.length) continue

            val isSplitterInRow = row[index] == '^'
            if (isSplitterInRow) {
                val leftBeamIndex = index - 1
                val rightBeamIndex = index + 1
                nextColIndexToBeams[leftBeamIndex] = nextColIndexToBeams.getOrDefault(leftBeamIndex, 0L) + beams
                nextColIndexToBeams[rightBeamIndex] = nextColIndexToBeams.getOrDefault(rightBeamIndex, 0L) + beams
            } else {
                nextColIndexToBeams[index] = nextColIndexToBeams.getOrDefault(index, 0L) + beams
            }
        }
        columnIndexToAmountOfBeams = nextColIndexToBeams
    }

    return columnIndexToAmountOfBeams.values.sum()
}

fun main() {
    val exampleInput = """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
    """.trim().lines() // 40 timelines

    val simplestOfSimplestExampleInput = """
.......S.......
.......|.......
......|^|......
......|.|......
.....|^|^|.....
    """.trim().lines() // 4 timelines

    val simplestExampleInput = """
.......S.......
.......|.......
......|^|......
......|.|......
.....|^|^|.....
.....|.|.|.....
....|^|||^|....
    """.trim().lines() // 6 timelines

    val simplerExampleInput = """
.......S.......
.......|.......
......|^|......
......|.|......
.....|^|^|.....
.....|.|.|.....
....|^|^|^|....
    """.trim().lines() // 8 timelines

    val simpleExampleInput = """
.......S.......
.......|.......
......|^|......
...............
.....|^|^|.....
...............
....|^|^|^|....
....^.^...^....
    """.trim().lines() // 13 timelines

    // note with explanation, to understand how beams splitting and creation of timelines work
    // beams:
    // 1 -> 2, 2 -> 3, 3 -> 4, 4 -> 5, ..
    // timelines:
    // 1 -> 2, 2 -> 4, 3 -> 8, 4 -> 16

    val individualInput = Path("src/day07/input.txt").readText().trim().lines()

    val sum = countAllTimelinesThatBeamSplitOpen(simpleExampleInput)
    println(sum)
}
